CREATE TABLE jun.board (
id INT(11) NOT NULL,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
author VARCHAR(45) NOT NULL,
count INT(11) NOT NULL DEFAULT 1,
date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id));