import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// import { authOptions } from './api/auth/[...nextauth]/route'
// import {getServerSession} from 'next-auth';
import Login from './components/login';
import AuthSession from './session';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.ico"
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const session = await getServerSession(authOptions)



  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
          <Login />
          {children}
        </AuthSession>
        </body>
    </html>
  )
}
