// nextjs에서 기본적으로 지원하는 loading 기능
export default function Loading(){
    return(
        <div className="fixed w-full h-full bg-black/50 top-0 left-0 z-50">
        <div className="absolute left-2/4 top-2/4 -translate-x-2/4 -translate-y-2/4">
          <svg
            width="200px"
            height="200px"
            viewBox="0 0 100 100"
            preserveAspectRatio="xMidYMid"
          >
            <g transform="rotate(0 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.9166666666666666s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(30 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.8333333333333334s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(60 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.75s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(90 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.6666666666666666s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(120 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.5833333333333334s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(150 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.5s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(180 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.4166666666666667s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(210 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.3333333333333333s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(240 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.25s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(270 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.16666666666666666s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(300 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="-0.08333333333333333s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
            <g transform="rotate(330 50 50)">
              <rect
                x="47"
                y="24"
                rx="3"
                ry="6"
                width="6"
                height="12"
                fill={`#ffa500`}
              >
                <animate
                  attributeName="opacity"
                  values="1;0"
                  keyTimes="0;1"
                  dur="1s"
                  begin="0s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
            </g>
          </svg>
        </div>
      </div>
    )
}

